### ISSUE TITLE
Sense Bubbles Are Not Fully Visible

### ISSUE THREAD

**Issue by jfeyas** [dfarache/Tabbed-Container-Extension#14]
Along the top of the visualization only the bottom third of the Sense "bubbles" for Snap Shot and Full Screen can be seen.    Although they do work if you get your mouse to click just right....

Please allow the bubbles to be fully visible.

**Comment by dfarache** [comment]
Which items would you say are missing? We are currently working on bringing the 'Details' into the extension.

which other bubbles are you missing?

**Comment by jfeyas** [comment]
Its the circles that appear on all Sense objects that have option for "take snap shot" and "full screen"  I attached an image of what I am seeing and what they should look like.  Thanks
![bug14](https://user-images.githubusercontent.com/21367195/27086271-b944a0b8-501f-11e7-9705-844e48f17cb6.png)
![bug14-2](https://user-images.githubusercontent.com/21367195/27086279-bd722d36-501f-11e7-929b-25761ea75f51.png)

**Comment by dfarache** [comment]
Solved by #15

**Comment by dfarache** [comment]
@jfeyas it should be fixed now
