### ISSUE TITLE
"Qlik Selection Menu" is getting hidden or cut off during selecting values

### ISSUE THREAD

**Issue by rvijayanth** [dfarache/Tabbed-Container-Extension#30]
Amazing extension. Allows us to accomplish a lot more within the same landscape. Have one minor issue:

"Qlik Selection Menu" is getting hidden or cut off during selecting values.

We are using two tabs and everything looks good until we make a selection. Once we make a selection, the lasso tool, clear selection, cancel and confirm selection menu thats shows up gets hidden or cut off. See screen shot. Im using IE11

![image](https://user-images.githubusercontent.com/4885651/28750504-83debca4-74bb-11e7-97e9-f6f22d2fa3ab.png)

Please help!

**Comment by rvijayanth** [comment]
Can anyone please help us?

**Comment by dfarache** [comment]
Hello rvijayanth,

Just came back from a long holiday. Sorry for making you wait.

I am working on this issue and I hope to be able to solve it soon.

**Comment by dfarache** [comment]
@rvijayanth  could you check #33 and tell me if it fixes the issue for you? If it does, I'll merge the changes

**Comment by dfarache** [comment]
@rvijayanth sorry, forgot to mention you

**Comment by dfarache** [comment]
After some testing we're pretty much positive that #33 solves this issue. @rvijayanth please feel free to reopen this issue if you still this happening
