### ISSUE TITLE
Issue if you resize the browser screen (Chrome)

### ISSUE THREAD

**Issue by marcoyukon** [dfarache/Tabbed-Container-Extension#31]
I noticed that when you resize the browser screen the content of the tab shrinks and won't expand when you expand the browser window back to its original size. You would have to "refresh" the page for the content of the active tab to also size back. It is a great extension and it would be nice if this is fixed. Qlik June 2017 SR1, Chrome build: 60.0.3112.90

**Comment by enaoki** [comment]
Same issue in IE 11.0.10240.17443 and Qlik june 2017 SR1.

**Comment by geck123** [comment]
Same issue in Chrome.  It would be great if this gets fixed.  Thanks.

**Comment by dfarache** [comment]
Hello to all,

I've created a pull request that I think, solves the issue (see #32).

Could someone verify that this solves the problem on your end before I merge it to master?

**Comment by geck123** [comment]
I tested it.  The new fix solved the problem.  Thanks a lot!!

**Comment by dfarache** [comment]
I am glad to hear that. I've just merged the fix to master. 

Closing the issue now. Feel free to reopen it if you still see this happening
