### ISSUE TITLE
Bar chart export from within tabbed container not working

### ISSUE THREAD

**Issue by SarahHLamb** [dfarache/Tabbed-Container-Extension#34]
Hi David,

I have created a bar chart with alternative dimensions and displayed this within a tabbed container.  However when I click on the export button within the tabbed container, the data that is exported doesn't resemble the data in the chart.

Please can you take a look and fix this bug?  I've attached a sample app for you to take a look and replicate the error.

Many thanks,

Sarah
 
[SL Tabbed Container Test.zip](https://github.com/dfarache/Tabbed-Container-Extension/files/1284495/SL.Tabbed.Container.Test.zip)

**Comment by dfarache** [comment]
Hi Sarah,

The export functionality is still in an experimental phase. It does not work so well on pivot tables or any type of visualization containing more than 2 mathematical dimensions.

I'm working on improving this feature and we hope to come up with a new release soon. I'll let you know once it's done.

Thanks for the feedback

**Comment by SarahHLamb** [comment]
Hi David,

Thank you for your quick response.  I look forward to the new release.

Sarah

**Comment by dfarache** [comment]
@SarahHLamb check out #35, the changes should solve your problem.

I am not merging it to master yet, as I also want to fix the same issue for pivot tables. Once that's done and thoroughly tested it will be merged.

**Comment by dfarache** [comment]
Hi again @SarahHLamb. I've just merged the pull request #35 which should solve this issue.

Please note that the data export feature does not support pivot tables yet.

**Comment by SarahHLamb** [comment]
Hi David,

That's great thank you.  Apologies I haven't had a chance to test this just yet.

Sarah
