### ISSUE TITLE
Invalid Visualization in IFrame

### ISSUE THREAD

**Issue by deltaspartan** [dfarache/Tabbed-Container-Extension#36]
When trying to use this object in an embedded iframe I get an "Invalid Visualization" error.  This extension appears to only work within the Qlik Sense hub.

**Comment by dfarache** [comment]
Hello @deltaspartan. Thanks for reporting this issue; I'll look into it.

Could you please tell me which version of QSense you're using?

While I fix the bug, you can add the TabbedContainer object to an external page using the Capabilities API.

**Comment by deltaspartan** [comment]
We are using version 3.2.
________________________________

**Comment by dfarache** [comment]
Hello @deltaspartan. Sorry for the delay. I've been quite busy.

Could you tell me if #37 solves your issue?

**Comment by zucoa** [comment]
Fixing the path to the cdn worked for me.

**Comment by dfarache** [comment]
Thanks for the feedback @zucoa. The pull request has been merged and I'm closing this issue now.

Feel free to reopen it if the issue persists.
