### ISSUE TITLE
Export to Excel loses filters

### ISSUE THREAD

**Issue by asmeiri** [dfarache/Tabbed-Container-Extension#47]
Hi team,
First I want to thank you for this awesome extension.
When I export the data the filter is lost and all data is exported.
Would appreciate your review on this issue.

Thanks

**Comment by dfarache** [comment]
@asmeiri thanks for the feedback. I have a couple of questions:

Do you have the latest version on the master branch?

What type of object are you trying to export?

**Comment by asmeiri** [comment]
Hi David,
Thank you for the quick response.

The qliksense version: 3.1 SR3

qliksense server : 10.7.2



The object i'v been trying to export is straight table.



I'v download the extension last time in 20/9/17.

It was updated since then?

**Comment by dfarache** [comment]
In theory, this issue has been solved. We noticed this behavior about 2 weeks ago.

I'd suggest pulling the master branch and trying again. let me know if that works for you.

**Comment by asmeiri** [comment]
Thank you. I will update you soon

**Comment by dfarache** [comment]
Hi @asmeiri. Any updates?

**Comment by dfarache** [comment]
I'm closing this issue, as it was  supposedly fixed in #43. Feel free to reopen it if you still see this behavior after pulling the latest version.

**Comment by asmeiri** [comment]
Hi David,
As you said, it works perfectly.
Sorry for the late response, IT only now approved the download of the
extension.

I would love to hear about your other extensions, tools and suggestions for
QlikSense if possible.

Sincerely yours,

Asaf Meiri

**Comment by dfarache** [comment]
Hi @asmeiri 

Glad to hear it's working.

We only have another extension open to the public: it's called AppLinker and it allows you to navigate between applications applying the same set of selections between them (a feature that used to be called Document Chaining in Qlik View).

We're always open to new ideas so feel free to email me if you have any cool thoughts for a Qlik Extension!
