### ISSUE TITLE
Export Table

### ISSUE THREAD

**Issue by jfeyas** [dfarache/Tabbed-Container-Extension#53]
There is an issue where the export to csv is skewed if your data already has a comma in it.  In my case its a company name in the format "Mega Company, Inc."  When this happens all columns following the company name get shifted to the right for that record.

**Comment by dfarache** [comment]
Hi @jfeyas 

Thanks for reporting the issue. Somebody reported the same issue a couple of days ago in #49 and we're really close to fixing it. 

Stay tuned for the next changes.
