### ISSUE TITLE
Color options - Can't Select

### ISSUE THREAD

**Issue by scaruthers86** [dfarache/Tabbed-Container-Extension#57]
When choosing a color option for the boarder or button color picker, the drop down menu doesn't expand to let me choose an option. Under the background color, I can type in a color code. 

Using 2017 Patch 1
![capture](https://user-images.githubusercontent.com/33726997/32899886-c5afe1fc-cab1-11e7-8bcf-e7da7877d49c.PNG)

**Comment by dfarache** [comment]
@scaruthers86 thank you for reporting this issue. Expect a fix soon

EDIT: I am afraid I was wrong. this issue has nothing to do with the code but with the new release; I have tried the extension on an older version of Qlik Sense and the color picker works.

I will talk to some people who might have a solution but this might take some time.

**Comment by scaruthers86** [comment]
Thank you

**Comment by dfarache** [comment]
Hello again @scaruthers86 ,

#58 should fix this issue. I've just merged it to master so feel fry to try it out.

Please do reopen this issue if the problem persists -which I hope won't be the case-.

**Comment by scaruthers86** [comment]
Fixed it!  Thank your for your fast work and updates!
