### ISSUE TITLE
export to Excel is Broken

### ISSUE THREAD

**Issue by kajapanisrikanth** [dfarache/Tabbed-Container-Extension#59]
Hello 
Firstly wonderful extension...thank you for your effort.

I tried to use the latest version and i still see the export to excel doesn't work as expected.

**Comment by dfarache** [comment]
hello @kajapanisrikanth 

thanks a lot for your feedback. which version are you using? the APIs have changed a bit with version 4 so that might be it.

Also, it'd be helpful if you attached a couple of screenshots with the console errors, if there are any.

EDIT: the feature works for Qlik Sense Desktop and Server versions 3.2 and September 2017 release. I am really going to need your help to fix this.

**Comment by kajapanisrikanth** [comment]
Hi David,

i tried using desktop version - September 2017 Patch2 and Enterprise Server November 2017.

when i tried to export to excel option both data columns show up in one column separated by a comma.
![app sheets - qlik sense](https://user-images.githubusercontent.com/14372838/33075259-20c70642-ce86-11e7-9614-0fcfe794ae59.png)

![excelissue](https://user-images.githubusercontent.com/14372838/33075175-d97f48bc-ce85-11e7-9705-ae9662b0fec7.png)


And also i get this pop up everytime.
![popuperror](https://user-images.githubusercontent.com/14372838/33075304-3c548c90-ce86-11e7-8878-27199a281752.png)

**Comment by dfarache** [comment]
Hi again @kajapanisrikanth 

I am really having issues reproducing this behavior. I even tried copying your data to an excel, creating the same object and then exporting it. The result I get is different from yours.

Is there any chance you could send a qvf to my email with this object?

EDIT: could you please tell me whether #60 solves your issue?

**Comment by kajapanisrikanth** [comment]
Hi David,

i was finally able to replicate my problem.
it is because i have my default list separator set a "|" instead of "," in windows.

https://superuser.com/questions/606272/how-to-get-excel-to-interpret-the-comma-as-a-default-delimiter-in-csv-files

After i changed my default seperator setting to back to ","...it started to work 
But it still had a bug when i set the format from auto to number.
![image](https://user-images.githubusercontent.com/14372838/33132561-3251cdee-cf57-11e7-803d-9dda99f03b41.png)

And it doesn't work on Ipad as it happens with regular export option in sense.

Update: i tried to use you new code update #60  and it solves the issue i pasted above but just the data formatting is gone.

**Comment by dfarache** [comment]
Hello again @kajapanisrikanth 

Could you please try again exporting using #60? I think it will now respect your formatting

**Comment by dfarache** [comment]
Hi, @kajapanisrikanth 

As said, I think #60 fixes the issue so I am closing it. Feel free to reopen it if you still experience it.
