### ISSUE TITLE
Please help with a problem when Exporting to Excel

### ISSUE THREAD

**Issue by annie8099** [dfarache/Tabbed-Container-Extension#62]
This is such a wonderful extension thank you for all your hard work and for sharing it.

We do, however, have one problem that I hope you can help us resolve.
I downloaded Version 2 of the app.  "Tabbed Container_V2" 
The Excel version we're on is Microsoft Excel 2010.
We have the problem when exporting data in a pivot table to excel.
The export creates a column for every comma (thousands separator) in the data.
Below is an example of the problem (if the attachments aren't showing I typed an example below).

**These are the measures in our pivot table:**
![pivottablewcommas](https://user-images.githubusercontent.com/6735586/33448058-018fe056-d5d3-11e7-8659-963a0c91da25.png)
**After we select the export button the excel file looks like this:**
![excelbad](https://user-images.githubusercontent.com/6735586/33448203-62d2caf4-d5d3-11e7-902f-3fb14c7186d7.png)
**If I remove the editing in the qlik sheet and just take out the commas as seen here:**
![pivottablewocommas](https://user-images.githubusercontent.com/6735586/33448274-92914acc-d5d3-11e7-9ed4-42b471f28ede.png)
**The excel looks great:**
![excelgood](https://user-images.githubusercontent.com/6735586/33448337-ba3e66ae-d5d3-11e7-9dd0-9d67cf7e049b.png)

The problem is we cannot exclude the commas in the editing because our numbers can be large and they become very hard to read.

If you could help us out with this problem the extension will be used a great deal in our Qlik Sense apps.

If the pictures aren't visible above, I typed an example of the problem:
**This is an example of a measure in our pivot table:**
$132,866

**After we select the export button the excel file looks like this:**
Column A     ColumnB
$132              866

**If I remove the editing in the qlik sheet and just take out the commas as seen here:**
$132866

**The excel looks great:**
Column A
$132,866

**Comment by dfarache** [comment]
Hello @annie8099 

This issue reminds me of #59. There is a pull request that kind of solves your issue: #60 

The only problem is that this "fix" will break your number formatting by removing the commas and the dolar sign, so I am hesitant about merging it to master. I am still thinking of better solutions.

For now, you could export your data as a tab-separated csv and then save the file as an excel,

**Comment by annie8099** [comment]
Thank you very much for your response.  
We ended up using "Sheet Navigation and Actions Button" extension.
You're tabbed extension will be used in the near future and I will let you know how our users make out using the csv and then saving the file as excel.  Thanks again!!

**Comment by dfarache** [comment]
ok. I will close this issue in the meantime, as it is the same as #59 

Do let me know when you use the extension again
